# Generated by Django 5.2.7 on 2025-10-28 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_refresh_token', models.TextField(blank=True, help_text='Encrypted Google refresh token', null=True)),
                ('last_refresh', models.DateTimeField(blank=True, help_text='Last time tokens were refreshed', null=True)),
                ('google_user_id', models.CharField(blank=True, help_text='Google user ID', max_length=255, null=True)),
                ('tokens_rotated_at', models.DateTimeField(blank=True, help_text='Last token rotation timestamp', null=True)),
                ('google_picture_url', models.URLField(blank=True, help_text='Google profile picture URL', max_length=500, null=True)),
                ('roles_storage', models.TextField(blank=True, default='[]', help_text='JSON string storing user roles', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
    ]
